### ISSUE TITLE
Genymotionのインストールができない

### ISSUE THREAD

**Issue by sarukiti** [Hayao0819/EG-Installer#4]
![image](https://user-images.githubusercontent.com/47556340/75538964-d8434600-5a5c-11ea-95aa-5a72c875bb37.png)

未割り当ての変数があるようです

**Comment by Hayao0819** [comment]
[問題を修正しました](https://github.com/Hayao0819/EG-Installer/commit/3a8a65180a0d98eb4c9d496b24d582dbeb3a0146)

**Comment by sarukiti** [comment]
まだ治ってないです…

**Comment by Hayao0819** [comment]
最新のコミットで修正しました
リリースまではしばらくお待ちください
